name: build_cpu-tagged

on:
  push:
    tags:
        - "*"

jobs:
  build_cpu-tagged:
    if: github.repository_owner == 'cmelab'
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set env "TAG"
        # Because this PR is triggered on tags
        # GITHUB_REF will be /refs/tags/THETAGNAME
        # the following parameter substitution will return only THETAGNAME
        # https://www.gnu.org/software/bash/manual/bash.html#Shell-Parameter-Expansion
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      -
        name: Check tag
        run: echo ${{ format('cmelab/grits:{0}', env.TAG) }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./containers/dockerfile_cpu
          push: true
          tags: ${{ format('cmelab/grits:{0}', env.TAG) }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
